### PR TITLE
Command line event selection

### PR DESCRIPTION
**Pull request by aaronwhite**

### CODE REVIEW

**Comment by lithin** [comment]
Hey looks great, thanks! :)

Any chance you could rename `jsFuncName` to `jsFunctionName`? Sorry for being so OCD, I just prefer having long version on names so it's absolutely obvious what it is.

Also could you write up some test cases for this change?

If you don't have time, let me know and I can help out :)

**Comment by aaronwhite** [comment]
Will do on both fronts

**Comment by Titozzz** [comment]
Any updates ? (kinda need this)
I can fix it if you want

**Comment by aaronwhite** [comment]
Fully intended to relieve you of the burden since you were kind enough to author the lib initially! But if you have need please do, I won't yet have a chance for another week :/

**Comment by mwawrusch** [comment]
Would be awesome if this could be merged. Makes the plugin actually useful.

**Comment by lithin** [comment]
@mwawrusch this functionality is now included in core serverless so you don't need this plugin anymore

**Pull request closed without merging**
